name       : python-xmltodict
version    : 0.13.0
release    : 5
source     :
    - https://pypi.python.org/packages/source/x/xmltodict/xmltodict-0.13.0.tar.gz : 341595a488e3e01a85a9d8911d8912fd922ede5fecc4dce437eb4b6c8d037e56
homepage   : https://github.com/martinblech/xmltodict
license    : MIT
component  : programming.python
summary    : Python module that makes working with XML feel like you are working with JSON
description: |
    xmltodict is a python module that makes working with XML feel like you are working with JSON
builddeps  :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
