name       : python-xmltodict
version    : 0.12.0
release    : 4
source     :
    - https://pypi.python.org/packages/source/x/xmltodict/xmltodict-0.12.0.tar.gz : 50d8c638ed7ecb88d90561beedbf720c9b4e851a9fa6c47ebd64e99d166d8a21
license    : MIT
component  : programming.python
summary    : Python module that makes working with XML feel like you are working with JSON
description: |
    xmltodict is a python module that makes working with XML feel like you are working with JSON
builddeps  :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test nosetests-%python3_version%
